# Generated by Django 6.0.4 on 2026-05-04 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=24)),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', '-date'], name='stocks_stoc_symbol_b0b1bf_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ví dụ: aapl.us (Stooq) hoặc VNM.VN (tuỳ nguồn)', max_length=24)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
